CREATE DATABASE INFOTOOLSSV
USE INFOTOOLSSV

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id_Usuario] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](100) NULL,
	[Clave] [varchar](100) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Usuarios] ADD PRIMARY KEY CLUSTERED 
(
	[Id_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_validar_usuario]
    @UserName VARCHAR(100),
    @Clave VARCHAR(100)
AS
BEGIN
    SELECT *
    FROM Usuarios
    WHERE UserName=@UserName and Clave=@Clave
END
GO
